/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Shared Study Logger API
 * OpenAPI spec version: 1.0.0
 */
import { apiMutator } from "../lib/api-mutator";
export interface ErrorResponse {
  error: string;
}

export type ResourceId = string;

export type Timestamp = string;

/**
 * @minimum 5
 * @maximum 1435
 */
export type DurationMinutes = number;

export type AvatarKey = (typeof AvatarKey)[keyof typeof AvatarKey];

export const AvatarKey = {
  avoidy: "avoidy",
  lavender: "lavender",
  fever: "fever",
  born: "born",
  innocence: "innocence",
  stolen: "stolen",
} as const;

export type UserRole = (typeof UserRole)[keyof typeof UserRole];

export const UserRole = {
  ADMIN: "ADMIN",
  USER: "USER",
} as const;

export type ReactionStamp = (typeof ReactionStamp)[keyof typeof ReactionStamp];

export const ReactionStamp = {
  thumbs_up: "thumbs_up",
  smile: "smile",
  laugh: "laugh",
  astonished: "astonished",
  cry: "cry",
  muscle: "muscle",
} as const;

export interface OkResponse {
  ok: true;
}

export interface LoginRequest {
  email: string;
  /** @minLength 1 */
  password: string;
}

export interface User {
  id: ResourceId;
  email: string;
  displayName: string;
  role: UserRole;
  /** @nullable */
  bio: string | null;
  avatarKey: AvatarKey | null;
  createdAt: Timestamp;
}

export interface UserResponse {
  user: User;
}

export interface UsersResponse {
  users: User[];
}

export interface PublicUser {
  id: ResourceId;
  displayName: string;
  /** @nullable */
  bio: string | null;
  avatarKey: AvatarKey | null;
  createdAt: Timestamp;
}

export interface PublicUserResponse {
  user: PublicUser;
}

export interface UpdateProfileRequest {
  /**
   * @minLength 1
   * @maxLength 50
   */
  displayName: string;
  /**
   * @maxLength 500
   * @nullable
   */
  bio: string | null;
  avatarKey: AvatarKey | null;
}

export interface ChangePasswordRequest {
  /** @minLength 1 */
  currentPassword: string;
  /**
   * @minLength 8
   * @maxLength 128
   */
  newPassword: string;
}

export interface Group {
  id: ResourceId;
  name: string;
  createdAt: Timestamp;
}

export interface GroupResponse {
  group: Group;
}

export interface GroupsResponse {
  groups: Group[];
}

export interface CreateAdminUserRequest {
  email: string;
  /**
   * @minLength 8
   * @maxLength 128
   */
  password: string;
  /**
   * @minLength 1
   * @maxLength 50
   */
  displayName: string;
}

export interface CreateAdminGroupRequest {
  /**
   * @minLength 1
   * @maxLength 100
   */
  name: string;
}

export interface AddGroupMemberRequest {
  userId: ResourceId;
}

export interface GroupMember {
  id: ResourceId;
  displayName: string;
  avatarKey: AvatarKey | null;
}

export interface GroupMembersResponse {
  members: GroupMember[];
}

export interface AdminMemberResponse {
  member: User;
}

export type AdminGroup = Group & {
  members: User[];
};

export interface AdminGroupsResponse {
  groups: AdminGroup[];
}

export interface ReactionSummary {
  stamp: ReactionStamp;
  /** @minimum 1 */
  count: number;
  reactedByMe: boolean;
}

export interface AddRecordReactionRequest {
  stamp: ReactionStamp;
}

export interface RecordReactionEntry {
  stamp: ReactionStamp;
  userId: ResourceId;
  displayName: string;
}

export interface RecordReactionResponse {
  reaction: RecordReactionEntry;
}

export interface RecordReactionsResponse {
  reactions: RecordReactionEntry[];
}

export interface StudyRecord {
  id: ResourceId;
  groupId: ResourceId;
  userId: ResourceId;
  authorDisplayName?: string;
  authorAvatarKey?: AvatarKey | null;
  studyDatetime: Timestamp;
  /** @minLength 1 */
  title: string;
  durationMinutes: DurationMinutes | null;
  /** @nullable */
  memo?: string | null;
  createdAt: Timestamp;
  updatedAt: Timestamp;
  reactions: ReactionSummary[];
}

export interface StudyRecordResponse {
  record: StudyRecord;
}

export interface StudyRecordsResponse {
  records: StudyRecord[];
  /** @nullable */
  nextCursor: string | null;
}

export interface CreateStudyRecordRequest {
  /** @nullable */
  studyDatetime: string | null;
  /**
   * @minLength 1
   * @maxLength 200
   */
  title: string;
  durationMinutes?: DurationMinutes | null;
  /** @maxLength 2000 */
  memo?: string;
}

export interface UpdateStudyRecordRequest {
  /** @nullable */
  studyDatetime: string | null;
  /**
   * @minLength 1
   * @maxLength 200
   */
  title: string;
  durationMinutes?: DurationMinutes | null;
  /** @maxLength 2000 */
  memo?: string;
}

export interface PushSubscriptionKeys {
  p256dh: string;
  auth: string;
}

export interface PushSubscription {
  endpoint: string;
  keys: PushSubscriptionKeys;
}

export interface PushUnsubscribeRequest {
  endpoint: string;
}

export interface VapidPublicKeyResponse {
  /** @minLength 1 */
  publicKey: string;
}

export interface InAppNotification {
  id: ResourceId;
  title: string;
  body: string;
  enabled: boolean;
  createdBy: ResourceId | null;
  createdAt: Timestamp;
  updatedAt: Timestamp;
}

export interface InAppNotificationResponse {
  notification: InAppNotification;
}

export interface InAppNotificationsResponse {
  notifications: InAppNotification[];
}

export interface CreateInAppNotificationRequest {
  /**
   * @minLength 1
   * @maxLength 200
   */
  title: string;
  /**
   * @minLength 1
   * @maxLength 2000
   */
  body: string;
  enabled?: boolean;
}

export interface UpdateInAppNotificationRequest {
  enabled: boolean;
}

export type XClientApiVersionParameter = string;

export type GetGroupRecordsParams = {
  cursor?: string;
  /**
   * @minimum 1
   * @maximum 100
   */
  limit?: number;
  /**
   * @maxItems 50
   */
  userIds?: ResourceId[];
};

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * @summary ログイン
 */
export const postAuthLogin = (
  loginRequest: LoginRequest,
  options?: SecondParameter<typeof apiMutator<UserResponse>>,
) => {
  return apiMutator<UserResponse>(
    {
      url: `/api/auth/login`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: loginRequest,
    },
    options,
  );
};

/**
 * @summary ログアウト
 */
export const postAuthLogout = (
  options?: SecondParameter<typeof apiMutator<OkResponse>>,
) => {
  return apiMutator<OkResponse>(
    { url: `/api/auth/logout`, method: "POST" },
    options,
  );
};

/**
 * @summary ログイン中ユーザー情報取得
 */
export const getAuthMe = (
  options?: SecondParameter<typeof apiMutator<UserResponse>>,
) => {
  return apiMutator<UserResponse>(
    { url: `/api/auth/me`, method: "GET" },
    options,
  );
};

/**
 * @summary プロフィール更新
 */
export const patchAuthMe = (
  updateProfileRequest: UpdateProfileRequest,
  options?: SecondParameter<typeof apiMutator<UserResponse>>,
) => {
  return apiMutator<UserResponse>(
    {
      url: `/api/auth/me`,
      method: "PATCH",
      headers: { "Content-Type": "application/json" },
      data: updateProfileRequest,
    },
    options,
  );
};

/**
 * @summary パスワード変更
 */
export const postAuthPassword = (
  changePasswordRequest: ChangePasswordRequest,
  options?: SecondParameter<typeof apiMutator<OkResponse>>,
) => {
  return apiMutator<OkResponse>(
    {
      url: `/api/auth/password`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: changePasswordRequest,
    },
    options,
  );
};

/**
 * @summary 公開プロフィール取得
 */
export const getUserById = (
  userId: string,
  options?: SecondParameter<typeof apiMutator<PublicUserResponse>>,
) => {
  return apiMutator<PublicUserResponse>(
    { url: `/api/users/${userId}`, method: "GET" },
    options,
  );
};

/**
 * @summary 所属グループ一覧
 */
export const getGroups = (
  options?: SecondParameter<typeof apiMutator<GroupsResponse>>,
) => {
  return apiMutator<GroupsResponse>(
    { url: `/api/groups`, method: "GET" },
    options,
  );
};

/**
 * @summary 所属メンバー一覧
 */
export const getGroupMembers = (
  groupId: string,
  options?: SecondParameter<typeof apiMutator<GroupMembersResponse>>,
) => {
  return apiMutator<GroupMembersResponse>(
    { url: `/api/groups/${groupId}/members`, method: "GET" },
    options,
  );
};

/**
 * @summary 学習記録一覧
 */
export const getGroupRecords = (
  groupId: string,
  params?: GetGroupRecordsParams,
  options?: SecondParameter<typeof apiMutator<StudyRecordsResponse>>,
) => {
  return apiMutator<StudyRecordsResponse>(
    { url: `/api/groups/${groupId}/records`, method: "GET", params },
    options,
  );
};

/**
 * @summary 学習記録投稿
 */
export const postGroupRecord = (
  groupId: string,
  createStudyRecordRequest: CreateStudyRecordRequest,
  options?: SecondParameter<typeof apiMutator<StudyRecordResponse>>,
) => {
  return apiMutator<StudyRecordResponse>(
    {
      url: `/api/groups/${groupId}/records`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: createStudyRecordRequest,
    },
    options,
  );
};

/**
 * @summary 学習記録編集
 */
export const patchGroupRecord = (
  groupId: string,
  recordId: string,
  updateStudyRecordRequest: UpdateStudyRecordRequest,
  options?: SecondParameter<typeof apiMutator<StudyRecordResponse>>,
) => {
  return apiMutator<StudyRecordResponse>(
    {
      url: `/api/groups/${groupId}/records/${recordId}`,
      method: "PATCH",
      headers: { "Content-Type": "application/json" },
      data: updateStudyRecordRequest,
    },
    options,
  );
};

/**
 * @summary 学習記録削除
 */
export const deleteGroupRecord = (
  groupId: string,
  recordId: string,
  options?: SecondParameter<typeof apiMutator<OkResponse>>,
) => {
  return apiMutator<OkResponse>(
    { url: `/api/groups/${groupId}/records/${recordId}`, method: "DELETE" },
    options,
  );
};

/**
 * @summary スタンプ一覧
 */
export const getRecordReactions = (
  groupId: string,
  recordId: string,
  options?: SecondParameter<typeof apiMutator<RecordReactionsResponse>>,
) => {
  return apiMutator<RecordReactionsResponse>(
    {
      url: `/api/groups/${groupId}/records/${recordId}/reactions`,
      method: "GET",
    },
    options,
  );
};

/**
 * @summary スタンプ付与
 */
export const postRecordReaction = (
  groupId: string,
  recordId: string,
  addRecordReactionRequest: AddRecordReactionRequest,
  options?: SecondParameter<typeof apiMutator<RecordReactionResponse>>,
) => {
  return apiMutator<RecordReactionResponse>(
    {
      url: `/api/groups/${groupId}/records/${recordId}/reactions`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: addRecordReactionRequest,
    },
    options,
  );
};

/**
 * @summary スタンプ取消
 */
export const deleteRecordReaction = (
  groupId: string,
  recordId: string,
  stamp: "thumbs_up" | "smile" | "laugh" | "astonished" | "cry" | "muscle",
  options?: SecondParameter<typeof apiMutator<OkResponse>>,
) => {
  return apiMutator<OkResponse>(
    {
      url: `/api/groups/${groupId}/records/${recordId}/reactions/${stamp}`,
      method: "DELETE",
    },
    options,
  );
};

/**
 * @summary VAPID 公開鍵取得
 */
export const getPushVapidPublicKey = (
  options?: SecondParameter<typeof apiMutator<VapidPublicKeyResponse>>,
) => {
  return apiMutator<VapidPublicKeyResponse>(
    { url: `/api/push/vapid-public-key`, method: "GET" },
    options,
  );
};

/**
 * @summary Push 購読登録
 */
export const postPushSubscribe = (
  pushSubscription: PushSubscription,
  options?: SecondParameter<typeof apiMutator<OkResponse>>,
) => {
  return apiMutator<OkResponse>(
    {
      url: `/api/push/subscribe`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: pushSubscription,
    },
    options,
  );
};

/**
 * @summary Push 購読解除
 */
export const deletePushSubscribe = (
  pushUnsubscribeRequest: PushUnsubscribeRequest,
  options?: SecondParameter<typeof apiMutator<OkResponse>>,
) => {
  return apiMutator<OkResponse>(
    {
      url: `/api/push/subscribe`,
      method: "DELETE",
      headers: { "Content-Type": "application/json" },
      data: pushUnsubscribeRequest,
    },
    options,
  );
};

/**
 * @summary 有効なアプリ内通知一覧
 */
export const getNotifications = (
  options?: SecondParameter<typeof apiMutator<InAppNotificationsResponse>>,
) => {
  return apiMutator<InAppNotificationsResponse>(
    { url: `/api/notifications`, method: "GET" },
    options,
  );
};

/**
 * @summary 全ユーザー一覧
 */
export const getAdminUsers = (
  options?: SecondParameter<typeof apiMutator<UsersResponse>>,
) => {
  return apiMutator<UsersResponse>(
    { url: `/api/admin/users`, method: "GET" },
    options,
  );
};

/**
 * @summary ユーザー作成
 */
export const postAdminUser = (
  createAdminUserRequest: CreateAdminUserRequest,
  options?: SecondParameter<typeof apiMutator<UserResponse>>,
) => {
  return apiMutator<UserResponse>(
    {
      url: `/api/admin/users`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: createAdminUserRequest,
    },
    options,
  );
};

/**
 * @summary 全グループ一覧（メンバー付き）
 */
export const getAdminGroups = (
  options?: SecondParameter<typeof apiMutator<AdminGroupsResponse>>,
) => {
  return apiMutator<AdminGroupsResponse>(
    { url: `/api/admin/groups`, method: "GET" },
    options,
  );
};

/**
 * @summary グループ作成
 */
export const postAdminGroup = (
  createAdminGroupRequest: CreateAdminGroupRequest,
  options?: SecondParameter<typeof apiMutator<GroupResponse>>,
) => {
  return apiMutator<GroupResponse>(
    {
      url: `/api/admin/groups`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: createAdminGroupRequest,
    },
    options,
  );
};

/**
 * @summary グループへユーザーを所属追加
 */
export const postAdminGroupMember = (
  groupId: string,
  addGroupMemberRequest: AddGroupMemberRequest,
  options?: SecondParameter<typeof apiMutator<AdminMemberResponse>>,
) => {
  return apiMutator<AdminMemberResponse>(
    {
      url: `/api/admin/groups/${groupId}/members`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: addGroupMemberRequest,
    },
    options,
  );
};

/**
 * @summary グループからユーザーの所属を削除
 */
export const deleteAdminGroupMember = (
  groupId: string,
  userId: string,
  options?: SecondParameter<typeof apiMutator<OkResponse>>,
) => {
  return apiMutator<OkResponse>(
    { url: `/api/admin/groups/${groupId}/members/${userId}`, method: "DELETE" },
    options,
  );
};

/**
 * @summary アプリ内通知の全件一覧
 */
export const getAdminNotifications = (
  options?: SecondParameter<typeof apiMutator<InAppNotificationsResponse>>,
) => {
  return apiMutator<InAppNotificationsResponse>(
    { url: `/api/admin/notifications`, method: "GET" },
    options,
  );
};

/**
 * @summary アプリ内通知の作成
 */
export const postAdminNotification = (
  createInAppNotificationRequest: CreateInAppNotificationRequest,
  options?: SecondParameter<typeof apiMutator<InAppNotificationResponse>>,
) => {
  return apiMutator<InAppNotificationResponse>(
    {
      url: `/api/admin/notifications`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: createInAppNotificationRequest,
    },
    options,
  );
};

/**
 * @summary アプリ内通知の有効/無効切替
 */
export const patchAdminNotification = (
  id: string,
  updateInAppNotificationRequest: UpdateInAppNotificationRequest,
  options?: SecondParameter<typeof apiMutator<InAppNotificationResponse>>,
) => {
  return apiMutator<InAppNotificationResponse>(
    {
      url: `/api/admin/notifications/${id}`,
      method: "PATCH",
      headers: { "Content-Type": "application/json" },
      data: updateInAppNotificationRequest,
    },
    options,
  );
};

/**
 * @summary アプリ内通知の削除
 */
export const deleteAdminNotification = (
  id: string,
  options?: SecondParameter<typeof apiMutator<OkResponse>>,
) => {
  return apiMutator<OkResponse>(
    { url: `/api/admin/notifications/${id}`, method: "DELETE" },
    options,
  );
};

export type PostAuthLoginResult = NonNullable<
  Awaited<ReturnType<typeof postAuthLogin>>
>;
export type PostAuthLogoutResult = NonNullable<
  Awaited<ReturnType<typeof postAuthLogout>>
>;
export type GetAuthMeResult = NonNullable<
  Awaited<ReturnType<typeof getAuthMe>>
>;
export type PatchAuthMeResult = NonNullable<
  Awaited<ReturnType<typeof patchAuthMe>>
>;
export type PostAuthPasswordResult = NonNullable<
  Awaited<ReturnType<typeof postAuthPassword>>
>;
export type GetUserByIdResult = NonNullable<
  Awaited<ReturnType<typeof getUserById>>
>;
export type GetGroupsResult = NonNullable<
  Awaited<ReturnType<typeof getGroups>>
>;
export type GetGroupMembersResult = NonNullable<
  Awaited<ReturnType<typeof getGroupMembers>>
>;
export type GetGroupRecordsResult = NonNullable<
  Awaited<ReturnType<typeof getGroupRecords>>
>;
export type PostGroupRecordResult = NonNullable<
  Awaited<ReturnType<typeof postGroupRecord>>
>;
export type PatchGroupRecordResult = NonNullable<
  Awaited<ReturnType<typeof patchGroupRecord>>
>;
export type DeleteGroupRecordResult = NonNullable<
  Awaited<ReturnType<typeof deleteGroupRecord>>
>;
export type GetRecordReactionsResult = NonNullable<
  Awaited<ReturnType<typeof getRecordReactions>>
>;
export type PostRecordReactionResult = NonNullable<
  Awaited<ReturnType<typeof postRecordReaction>>
>;
export type DeleteRecordReactionResult = NonNullable<
  Awaited<ReturnType<typeof deleteRecordReaction>>
>;
export type GetPushVapidPublicKeyResult = NonNullable<
  Awaited<ReturnType<typeof getPushVapidPublicKey>>
>;
export type PostPushSubscribeResult = NonNullable<
  Awaited<ReturnType<typeof postPushSubscribe>>
>;
export type DeletePushSubscribeResult = NonNullable<
  Awaited<ReturnType<typeof deletePushSubscribe>>
>;
export type GetNotificationsResult = NonNullable<
  Awaited<ReturnType<typeof getNotifications>>
>;
export type GetAdminUsersResult = NonNullable<
  Awaited<ReturnType<typeof getAdminUsers>>
>;
export type PostAdminUserResult = NonNullable<
  Awaited<ReturnType<typeof postAdminUser>>
>;
export type GetAdminGroupsResult = NonNullable<
  Awaited<ReturnType<typeof getAdminGroups>>
>;
export type PostAdminGroupResult = NonNullable<
  Awaited<ReturnType<typeof postAdminGroup>>
>;
export type PostAdminGroupMemberResult = NonNullable<
  Awaited<ReturnType<typeof postAdminGroupMember>>
>;
export type DeleteAdminGroupMemberResult = NonNullable<
  Awaited<ReturnType<typeof deleteAdminGroupMember>>
>;
export type GetAdminNotificationsResult = NonNullable<
  Awaited<ReturnType<typeof getAdminNotifications>>
>;
export type PostAdminNotificationResult = NonNullable<
  Awaited<ReturnType<typeof postAdminNotification>>
>;
export type PatchAdminNotificationResult = NonNullable<
  Awaited<ReturnType<typeof patchAdminNotification>>
>;
export type DeleteAdminNotificationResult = NonNullable<
  Awaited<ReturnType<typeof deleteAdminNotification>>
>;
